# -*- coding: utf-8 -*-
"""semantic_question_retrieval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSE5giLqrlPcb5zuk4lzwxmQFthNC6wS
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("quora/question-pairs-dataset")

print("Path to dataset files:", path)

"""# Imports"""

import os
import pandas as pd
import kagglehub

from sentence_transformers import SentenceTransformer
from sklearn.neighbors import NearestNeighbors

"""# Find and Load CSV"""

for file in os.listdir(path):
    if file.endswith(".csv"):
        csv_path = os.path.join(path,file)

df = pd.read_csv(csv_path)

df.head()

"""# Create Question Corpus for Retrieval"""

questions = pd.concat(
    [df["question1"], df["question2"]]
).dropna().head(10000).tolist()

print("Questions indexed:",len(questions))

"""# Load Sentence Embedding Model"""

model = SentenceTransformer(
'all-mpnet-base-v2'
)

"""# Generate Semantic Embeddings"""

embeddings = model.encode(
    questions,
    show_progress_bar=True
)

"""# Train Nearest Neighbor Retrieval Model"""

nn = NearestNeighbors(
    n_neighbors=6,
    metric='cosine'
)

nn.fit(embeddings)

print("Retrieval model ready")

"""# Retrieval Function"""

def retrieve_similar(query):

    query_embedding = model.encode([query])

    distances,indices = nn.kneighbors(
        query_embedding
    )

    print("\nQuery:")
    print(query)

    print("\nSimilar Questions:\n")

    for i in indices[0][1:]:
        print("-",questions[i])

"""# User Query"""

query = input("Write a query to check other similar questions: ")
retrieve_similar(query)

"""# Jaccard Similarity Function"""

q2 = input("Write another query to check its similarity: ")

def jaccard_similarity(a,b):

    A=set(a.lower().split())
    B=set(b.lower().split())

    return len(A&B)/len(A|B)

    q1= query
print(jaccard_similarity(q1,q2))

"""# Determine the Threshold"""

query_embedding=model.encode([query])

distances,indices=nn.kneighbors(
    query_embedding,
    n_neighbors=6
)

for i,d in zip(indices[0][1:],distances[0][1:]):

    sim=1-d

    print(round(sim,3), " | ", questions[i])

"""# Evaluation"""

threshold=0.40
k=5


query_embedding=model.encode([query])

distances,indices=nn.kneighbors(
    query_embedding,
    n_neighbors=k+1
)

similarities=[]
relevant=0


for d in distances[0][1:]:

    sim=1-d
    similarities.append(sim)

    if sim>=threshold:
        relevant+=1


precision=relevant/k
accuracy=precision*100
avg_sim=sum(similarities)/len(similarities)


print("------ MODEL EVALUATION ------")
print("Query:",query)

print("\nPrecision@5:",
      round(precision,2))

print("Retrieval Accuracy:",
      round(accuracy,2),"%")

print("Average Cosine Similarity:",
      round(avg_sim,3))

print("Highest Similarity:",
      round(max(similarities),3))

print("Lowest Similarity:",
      round(min(similarities),3))

print("Relevant Results:",
      relevant,"out of",k)

"""Since this is a retrieval and ranking problem rather than a pure classification problem, evaluation is better done using Precision@K and related retrieval metrics instead of standard classification accuracy."""